import type { SeatPosition, TableDemoView } from './table.types';

const positions = [
  'bottom-center',
  'lower-left',
  'upper-left',
  'top-center',
  'upper-right',
  'lower-right',
] as const satisfies readonly SeatPosition[];

export const activeDemoTable = {
  mode: 'demo',
  variant: 'active',
  isHandActive: true,
  roomName: 'The Lantern Room',
  roomCode: 'FELT7K2Q',
  smallBlind: 50,
  bigBlind: 100,
  isHost: true,
  street: 'Turn',
  pot: 4_850,
  board: [
    { rank: 'Q', suit: 'clubs' },
    { rank: '9', suit: 'diamonds' },
    { rank: '7', suit: 'spades' },
    { rank: '2', suit: 'hearts' },
  ],
  seats: [
    {
      kind: 'occupied',
      seatIndex: 0,
      position: positions[0],
      nickname: 'Mara',
      stack: 7_850,
      contribution: 250,
      state: 'active',
      isHero: true,
      isActing: true,
      isDealer: false,
      blind: null,
      cards: [
        { rank: 'A', suit: 'spades' },
        { rank: 'K', suit: 'hearts' },
      ],
    },
    {
      kind: 'occupied',
      seatIndex: 1,
      position: positions[1],
      nickname: 'Sol',
      stack: 12_400,
      contribution: 600,
      state: 'active',
      isHero: false,
      isActing: false,
      isDealer: true,
      blind: null,
      cards: 'concealed',
    },
    {
      kind: 'occupied',
      seatIndex: 2,
      position: positions[2],
      nickname: 'Vale',
      stack: 0,
      contribution: 600,
      state: 'all-in',
      isHero: false,
      isActing: false,
      isDealer: false,
      blind: 'small-blind',
      cards: 'concealed',
    },
    {
      kind: 'occupied',
      seatIndex: 3,
      position: positions[3],
      nickname: 'June',
      stack: 9_200,
      contribution: null,
      state: 'sitting-out',
      isHero: false,
      isActing: false,
      isDealer: false,
      blind: null,
      cards: null,
    },
    {
      kind: 'occupied',
      seatIndex: 4,
      position: positions[4],
      nickname: 'Rook',
      stack: 6_500,
      contribution: 150,
      state: 'folded',
      isHero: false,
      isActing: false,
      isDealer: false,
      blind: null,
      cards: 'concealed',
    },
    {
      kind: 'occupied',
      seatIndex: 5,
      position: positions[5],
      nickname: 'Niko',
      stack: 15_100,
      contribution: 600,
      state: 'active',
      isHero: false,
      isActing: false,
      isDealer: false,
      blind: 'big-blind',
      cards: 'concealed',
    },
  ],
  legalActions: {
    canFold: true,
    canCheck: false,
    call: { chips: 350, total: 600 },
    wager: {
      kind: 'raise',
      minimum: 1_200,
      maximum: 8_100,
      initial: 2_400,
    },
  },
  liveActions: null,
  handCompletion: null,
  roomPanel: {
    members: [
      { nickname: 'Mara', status: 'Playing', stack: 7_850, isHost: true },
      { nickname: 'Sol', status: 'Playing', stack: 12_400, isHost: false },
      { nickname: 'Vale', status: 'All in', stack: 0, isHost: false },
      { nickname: 'June', status: 'Sitting out', stack: 9_200, isHost: false },
      { nickname: 'Rook', status: 'Folded', stack: 6_500, isHost: false },
      { nickname: 'Niko', status: 'Playing', stack: 15_100, isHost: false },
    ],
    seatRequests: [],
    canStartHand: false,
  },
  chat: [
    { id: 'chat-1', sender: 'Mara', message: 'nice hand', timestamp: '12:46' },
    {
      id: 'chat-2',
      sender: 'Niko',
      message: 'one more orbit?',
      timestamp: '12:47',
    },
    { id: 'chat-3', sender: 'Sol', message: 'gl', timestamp: '12:48' },
  ],
} satisfies TableDemoView;

export const openDemoTable = {
  mode: 'demo',
  variant: 'open',
  isHandActive: false,
  roomName: 'The Lantern Room',
  roomCode: 'FELT7K2Q',
  smallBlind: 50,
  bigBlind: 100,
  isHost: true,
  street: 'Open table',
  pot: 0,
  board: [],
  seats: [
    {
      kind: 'occupied',
      seatIndex: 0,
      position: positions[0],
      nickname: 'Mara',
      stack: 10_000,
      contribution: null,
      state: 'seated',
      isHero: true,
      isActing: false,
      isDealer: false,
      blind: null,
      cards: null,
    },
    {
      kind: 'occupied',
      seatIndex: 1,
      position: positions[1],
      nickname: 'Sol',
      stack: 10_000,
      contribution: null,
      state: 'seated',
      isHero: false,
      isActing: false,
      isDealer: true,
      blind: null,
      cards: null,
    },
    { kind: 'empty', seatIndex: 2, position: positions[2] },
    {
      kind: 'occupied',
      seatIndex: 3,
      position: positions[3],
      nickname: 'June',
      stack: 10_000,
      contribution: null,
      state: 'sitting-out',
      isHero: false,
      isActing: false,
      isDealer: false,
      blind: null,
      cards: null,
    },
    { kind: 'empty', seatIndex: 4, position: positions[4] },
    {
      kind: 'occupied',
      seatIndex: 5,
      position: positions[5],
      nickname: 'Niko',
      stack: 10_000,
      contribution: null,
      state: 'seated',
      isHero: false,
      isActing: false,
      isDealer: false,
      blind: null,
      cards: null,
    },
  ],
  legalActions: null,
  liveActions: null,
  handCompletion: null,
  roomPanel: {
    members: [
      { nickname: 'Mara', status: 'Seated', stack: 10_000, isHost: true },
      { nickname: 'Sol', status: 'Seated', stack: 10_000, isHost: false },
      { nickname: 'June', status: 'Sitting out', stack: 10_000, isHost: false },
      { nickname: 'Niko', status: 'Seated', stack: 10_000, isHost: false },
      { nickname: 'Ember', status: 'In room', stack: null, isHost: false },
    ],
    seatRequests: [{ nickname: 'Ember', seatIndex: 2 }],
    canStartHand: true,
  },
  chat: [
    { id: 'chat-1', sender: 'Mara', message: 'nice hand', timestamp: '12:46' },
    {
      id: 'chat-2',
      sender: 'Niko',
      message: 'one more orbit?',
      timestamp: '12:47',
    },
    { id: 'chat-3', sender: 'Sol', message: 'gl', timestamp: '12:48' },
  ],
} satisfies TableDemoView;

export function demoTableForVariant(variant: string | null): TableDemoView {
  return variant === 'open' ? openDemoTable : activeDemoTable;
}
